export const LOGIN_USER_START='LOGIN_USER_START';
export const LOGIN_USER_FINISH='LOGIN_USER_FINISH';
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL';
export const REGISTER_USER_START='REGISTER_USER_START';
export const REGISTER_USER_FINISH='REGISTER_USER_FINISH';
export const REGISTER_USER_FAIL='REGISTER_USER_FAIL';


